<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="MyEcore" nsURI="platform:/plugin/tdt4250/model/my.ecore" nsPrefix="MyEcore">
  <eClassifiers xsi:type="ecore:EClass" name="School">
    <eStructuralFeatures xsi:type="ecore:EReference" name="programs" upperBound="-1"
        eType="#//Program" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="schoolName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="students" eType="#//Student"
        containment="true" eOpposite="#//Student/school"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Program">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="programName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="programCreditRequirements"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="programYear" eType="#//Year"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Year">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ordinaryPrograms" eType="#//ProgramWithNoSpecialication"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="programsWithSpecialisation"
        eType="#//ProgramWithSpecialisation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="year" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProgramWithNoSpecialication" eSuperTypes="#//Program">
    <eStructuralFeatures xsi:type="ecore:EReference" name="semsters" eType="#//Semester"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProgramWithSpecialisation" eSuperTypes="#//Program">
    <eStructuralFeatures xsi:type="ecore:EReference" name="specilisations" eType="#//Specialisation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Specialisation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="semesters" eType="#//Semester"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Semester">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="hasEnoughCredits"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="electiveCourses" upperBound="-1"
        eType="#//Course" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mandatoryCourses" eType="#//Course"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="semesterCreditRequirements"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Course">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="correctCredit"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="credit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Student">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="school" eType="#//School"
        eOpposite="#//School/students"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="individualStudyPlan" eType="#//IndividualStudyPlan"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndividualStudyPlan">
    <eStructuralFeatures xsi:type="ecore:EReference" name="selectedSemesters" upperBound="-1"
        eType="#//SelectedSemester" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="results" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelectedSemester">
    <eStructuralFeatures xsi:type="ecore:EReference" name="semesters" eType="#//Semester"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="semesterName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
