<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="MyEcore" nsURI="platform:/plugin/tdt4250/model/my.ecore" nsPrefix="MyEcore">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="validationDelegates" value="http://www.eclipse.org/acceleo/query/1.0"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="School">
    <eStructuralFeatures xsi:type="ecore:EReference" name="programsWithNoSpecialication"
        upperBound="-1" eType="#//ProgramWithNoSpecialication" containment="true"
        eOpposite="#//ProgramWithNoSpecialication/school"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="schoolName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="students" upperBound="-1"
        eType="#//Student" containment="true" eOpposite="#//Student/school"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="programsWithSpecialications"
        upperBound="-1" eType="#//ProgramWithSpecialisation" containment="true" eOpposite="#//ProgramWithSpecialisation/school"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Program">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="programName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="programCreditRequirements"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Year">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="year" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specilisations" upperBound="-1"
        eType="#//Specialisation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="semsters" upperBound="-1"
        eType="#//Semester" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProgramWithNoSpecialication" eSuperTypes="#//Program">
    <eStructuralFeatures xsi:type="ecore:EReference" name="programYear" upperBound="-1"
        eType="#//Year" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="school" eType="#//School"
        eOpposite="#//School/programsWithNoSpecialication"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProgramWithSpecialisation" eSuperTypes="#//Program">
    <eStructuralFeatures xsi:type="ecore:EReference" name="programSpecialicationYear"
        upperBound="-1" eType="#//Year" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="school" eType="#//School"
        eOpposite="#//School/programsWithSpecialications"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Specialisation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="semesters" upperBound="-1"
        eType="#//Semester" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="newSpecialication" upperBound="-1"
        eType="#//Specialisation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Semester">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="semesterHasEnoughCredit"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/acceleo/query/1.0">
      <details key="semesterHasEnoughCredit" value="((self.electiveCourses->collect(e | e.credit)->sum()) + (self.mandatoryCourses->collect(e | e.credit)->sum())) >=30.0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="year" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="electiveCourses" upperBound="-1"
        eType="#//Course" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mandatoryCourses" upperBound="-1"
        eType="#//Course" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SemesterKind" eType="#//SemesterKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SemesterKind">
    <eLiterals name="Autumn" value="1"/>
    <eLiterals name="Fall"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CourseLevel">
    <eLiterals name="HigherGradeLevel"/>
    <eLiterals name="ThirdYearLevel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Course">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="correctCredit"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="#//CourseCode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="credit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fallOrAutumnCourse" eType="#//SemesterKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="CourseCode" instanceClassName="java.lang.String"/>
  <eClassifiers xsi:type="ecore:EClass" name="Student">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="nameCharacters"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="school" eType="#//School"
        eOpposite="#//School/students"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="individualStudyPlan" eType="#//IndividualStudyPlan"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndividualStudyPlan">
    <eStructuralFeatures xsi:type="ecore:EReference" name="selectedSemesters" upperBound="-1"
        eType="#//SelectedSemester" containment="true" eOpposite="#//SelectedSemester/studyPlan"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="results" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelectedSemester">
    <eOperations name="addCourseToSemester" eType="#//SelectedSemester" eExceptions="#//Course"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="semesters" eType="#//Semester"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="semesterName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="studyPlan" eType="#//IndividualStudyPlan"
        eOpposite="#//IndividualStudyPlan/selectedSemesters"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selectableCourses" eType="#//Course"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
