<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="programmes" nsURI="platform:/plugin/no.tdt4250.model/programmes.ecore"
    nsPrefix="programmes">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="validationDelegates" value="http://www.eclipse.org/acceleo/query/1.0"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="School">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="#//Name"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="programs" upperBound="-1"
        eType="#//Program" containment="true" eOpposite="#//Program/school"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Program">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="#//Name"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="programYears" upperBound="-1"
        eType="#//Year" containment="true" eOpposite="#//Year/program"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="school" eType="#//School"
        eOpposite="#//School/programs"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="creditRequirment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Year">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="correctYearFormat"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/acceleo/query/1.0">
      <details key="correctYearFormat" value="self.year.size() == 4 AND self.year.matches('[0-9]')"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="year" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="program" eType="#//Program"
        eOpposite="#//Program/programYears"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="semesters" upperBound="-1"
        eType="#//ProgramSemester" containment="true" eOpposite="#//ProgramSemester/ProgramYear"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Specialization">
    <eStructuralFeatures xsi:type="ecore:EReference" name="specializesIn" eType="#//Program"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="#//Name"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="semsters" upperBound="-1"
        eType="#//ProgramSemester" containment="true" eOpposite="#//ProgramSemester/currentSpecialisation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="semesterSpecialization"
        eType="#//ProgramSemester" eOpposite="#//ProgramSemester/specializations"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProgramSemester">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="courseTypeEqualsSemesterType"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/acceleo/query/1.0">
      <details key="courseTypeEqualsSemesterType" value="if(self.specializations->size() &lt; 1)  then (self.electiveCourses->forAll(course | course.courseSemesterType.value == self.SemesterKind.value)) else (self.specializations->forAll(specialization | specialization.semsters->forAll(semester | semester.electiveCourses->forAll(course | (course.courseSemesterType.value == semester.SemesterKind.value)))) endif"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Year" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SemesterKind" eType="#//SemesterKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mandatoryCourses" upperBound="-1"
        eType="#//Course" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="electiveCourses" upperBound="-1"
        eType="#//Course" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ProgramYear" eType="#//Year"
        eOpposite="#//Year/semesters"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specializations" upperBound="-1"
        eType="#//Specialization" containment="true" eOpposite="#//Specialization/semesterSpecialization"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentSpecialisation"
        eType="#//Specialization" eOpposite="#//Specialization/semsters"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Course">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="correctCrtedit hasCredit"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/acceleo/query/1.0">
      <details key="hasCredit" value="self.credits != null"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="#//CourseCode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="#//Name"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="courseSemesterType" eType="#//SemesterKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="credits" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" eType="#//CourseLevel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SemesterKind">
    <eLiterals name="Fall" value="1"/>
    <eLiterals name="Spring" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CourseLevel">
    <eLiterals name="ThirdYearLevel" value="1"/>
    <eLiterals name="HigherDegreeLevel" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="CourseCode" instanceClassName="java.lang.String">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="pattern" value="\p{L}+\d+"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Name" instanceClassName="java.lang.String">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="maxLength" value="50"/>
      <details key="minLength" value="3"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
